[package]
name = "moonlight-common-sys"
version.workspace = true
edition = "2024"
license = { workspace = true }

[dependencies]
openssl-sys = { workspace = true }
printf-compat = "0.4.0"

[features]
default = ["vendored", "openssl-sys/vendored"]

# Moonlight Features
crypto = []


# Vendored
vendored = ["dep:cmake"]

[build-dependencies]
bindgen = { workspace = true }
cmake = { workspace = true, optional = true }
